### ISSUE TITLE
Feature Request: Work with local Nx CLI installation

### ISSUE THREAD

**Issue by nartc** [jscutlery/nx-completion#1]
Hi,

This is such a nice plugin that I don't realize I want. However, like many people, I don't usually have `Nx CLI` installed globally and use `yarn nx` (or `npx nx`) to invoke the locally installed `nx` instead. 

That said, would it be possible to support `yarn nx` as well?

Thanks

**Comment by edbzn** [comment]
@nartc I close this with the answer I gave you on Twitter: 

Unfortunately I think it's not possible using compdef, command definition is static and should start with `nx` to trigger the completion. But I think using Nx globally is fine since it handles local version mismatch pretty well.
