### ISSUE TITLE
Format arguments to camel-case

### ISSUE THREAD

**Issue by edbzn** [jscutlery/nx-completion#4]
All arguments should be formatted in camel-case, eg: `--i18nLocale` instead of `--i18n-locale`.

**Comment by amoghrajesh** [comment]
@edbzn I would like to work on this issue. Let me know how I can onboard myself and how I can contribute.
I would like to know how to test it etc too

**Comment by edbzn** [comment]
Hi @amoghrajesh, you can clone the repository, make the changes, source the code you have changed: `source /<path-to-the-plugin>/nx-completion.plugin.zsh` and try to type nx in the console to see the completion. Then push your changes and open a PR!

**Comment by amoghrajesh** [comment]
@edbzn could you assign this issue to me so I can work with you on this to solve this one?

**Comment by amoghrajesh** [comment]
@edbzn I am trying to onboard onto this task and it keeps saying `zsh: command not found: nx` even though I have edited by ~.zshrc file already

**Comment by amoghrajesh** [comment]
@edbzn I need some more background / context to operate on this issue. Could you let me know how I can onboard to understand it?

**Comment by edbzn** [comment]
@amoghrajesh All arguments are formatted in kebab-case actualy, for example: 

```bash
        "--browser-target[Target to extract from.]:target:" \
        "--i18n-format[Format of the localization file specified with --i18n-file.]:format:" \
```

The best would be camel-case instead, I would expect something like: 

```bash
        "--browserTarget[Target to extract from.]:target:" \
        "--i18nFormat[Format of the localization file specified with --i18nFile.]:format:" \
```

etc... the list is quite long.

**Comment by Alireza-Sampour** [comment]
If the issue is still there I would like to work on this.

**Comment by edbzn** [comment]
@Alireza-Sampour go ahead!

**Comment by Alireza-Sampour** [comment]
I created a pull request, let me know if anything is forgotten.

**Comment by edbzn** [comment]
@Alireza-Sampour Thanks for the work!
