### ISSUE TITLE
Support for npx and other ways to use `nx` without having it installed globally

### ISSUE THREAD

**Issue by dianjuar** [jscutlery/nx-completion#7]
I use `nx` with `npx` because I don't want to deal with update my global install and I can use the version installed on each project, not the global one.

There is a way to use your plugin to have compatibility with `npx` and other ways to use `nx` without having it installed globally (like `yarn` and `npm`)?

**Comment by edbzn** [comment]
Unfortunately, it's not possible using compdef, command definition is static and should start with nx to trigger the completion. But I think using Nx globally is fine since it handles local version mismatch pretty well.

**Comment by dianjuar** [comment]
Ok, I understand.

Also, as a workaround, I would try to create an alias on my system `alias nx="npx nx"`. If this works I would close this issue.

**Comment by edbzn** [comment]
I think it won't work because compdef will receive "npx" under the hood, completion won't be triggered.

**Comment by dianjuar** [comment]
Yes, you are right, is not working.

Well. I supposed that I will close this issue

**Comment by Amdrel** [comment]
There actually is a solution to this that I found that I would like to share. Instead of using an alias, you can use a function instead. Using this function while navigated inside of an Nx project gives me functional autocomplete.

```zsh
function nx() {
    npx nx "$@"
}
```

**Comment by rene-leanix** [comment]
Another option is to add `./node_modules/.bin/` to the path to make all local binaries available without `npx`:

```
export PATH="./node_modules/.bin/:$PATH"
```
